name: build-test
on:
  push:
    branches:
      - 'main'
      - 'release-**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # pin@v4.1.2
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # pin@4.1.0
        with:
          go-version: '1.21'
      - name: Test source headers are present
        run: make test-source-headers
      - name: Run unit tests
        run: make test-coverage
      - name: Test build
        run: make build
